# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marqin's BnS stuff.
description: > # this means to ignore newlines until "baseurl:"
  BnS related stuff (eg. Daily Challenge info).
baseurl: "/bns" # the subpath of your site, e.g. /blog
url: "https://marqin.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Social
twitter_username: mrMarqin
github_username: Marqin
